services:
  dev:
    build: .
    image: tdd_chat_app_app:latest
    container_name: tdd_chat_app_dev
    volumes:
      - ./tdd_chat_app:/app/tdd_chat_app
    ports:
      - 8000:8000
    env_file:
      - .docker.env
