volumes:
    tdd_chat_app_postgres_1:
    tdd_chat_app_postgres_2:
    tdd_chat_app_postgres_3:

services:
  dev:
    build: .
    image: tdd_chat_app_app:latest
    container_name: tdd_chat_app_dev
    volumes:
      - ./tdd_chat_app:/app/tdd_chat_app
      - ./config.yaml:/app/config.yaml
    ports:
      - 8000:8000
    environment:
        - CONFIG_YAML=/app/config.yaml
    env_file:
      - .docker.env
    depends_on:
      - postgres_1
      - postgres_2
      - postgres_3


  postgres_1:
      image:  postgres:15.6-bullseye
      container_name: postgres_15_tdd_chat_app_1
      environment:
        - POSTGRES_PASSWORD=postgres
      ports:
        - "15432:5432"
      volumes:
        - tdd_chat_app_postgres_1:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5


  postgres_2:
      image:  postgres:15.6-bullseye
      container_name: postgres_15_tdd_chat_app_2
      environment:
        - POSTGRES_PASSWORD=postgres
      ports:
        - "25432:5432"
      volumes:
        - tdd_chat_app_postgres_2:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  postgres_3:
      image:  postgres:15.6-bullseye
      container_name: postgres_15_tdd_chat_app_3
      environment:
        - POSTGRES_PASSWORD=postgres
      ports:
        - "35432:5432"
      volumes:
        - tdd_chat_app_postgres_3:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
