cache-dir = "./.poetry_cache"

[experimental]
system-git-client = true

[installer]
#max-workers = null
#no-binary = null
#parallel = true

[virtualenvs]
create = true
path = "./.virtualenvs"
prompt = "{project_name}-py-{python_version}"
prefer-active-python = false

#in-project = true

[virtualenvs.options]
always-copy = true
no-pip = false
no-setuptools = false
system-site-packages = false
